### ISSUE TITLE
"Select for feature comparison" tooltip gets stuck open on Android

### ISSUE THREAD

**Issue by VorpalBlade** [Systemcluster/unstablerust#1]
Using the Brave browser on Android, when I click the arrow in a circle, the "Select for feature comparison" tooltip gets stuck open until I click another link. On a phone in portrait mode this goes off the side of the screen (so not too bad, but also you can't read the tooltip), but on a tablet this ends up on top of the feature list instead, making part of the list unreadable.

**Comment by Systemcluster** [comment]
Thanks for the report! Sorry that it took a while, but the tooltips should now be dismissable with a click/tap anywhere.

**Comment by VorpalBlade** [comment]
Seems solved, can't see the tool tip at all on mobile any longer.
