### ISSUE TITLE
a[0] is undefined

### ISSUE THREAD

**Issue by matthiaskrgr** [Systemcluster/unstablerust#2]
something broke :(
https://unstablerust.dev/
![image](https://github.com/user-attachments/assets/14f89dd5-2732-49e8-9a46-240ca141ac07)

**Comment by Systemcluster** [comment]
Thanks for the report! It looks like something changed in the sources, I'll check it out.

**Comment by Systemcluster** [comment]
Fixed in 3f5392afd058aa9d99c5a7faf3eae1f193c7902c!
